[package]

name = "markov"
version = "0.0.6"
description = "A generic markov chain implementation in Rust."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "MPL-2.0"
keywords = ["markov", "chain", "probability"]
documentation = "http://www.rust-ci.org/aaronweiss74/markov/doc/markov/"
repository = "https://github.com/aaronweiss74/markov"
readme = "README.md"
