[package]

name = "markov"
version = "0.0.7"
description = "A generic markov chain implementation in Rust."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "Unlicense"
keywords = ["markov", "chain", "probability"]
documentation = "http://www.rust-ci.org/aatxe/markov/doc/markov/"
repository = "https://github.com/aatxe/markov"
readme = "README.md"

[dependencies.rustc-serialize]

rustc-serialize = "~0.1.4"
