[package]

name = "markov"
version = "0.0.17"
description = "A generic markov chain implementation in Rust."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "Unlicense"
keywords = ["markov", "chain", "probability"]
documentation = "http://aatxe.github.io/markov/markov/"
repository = "https://github.com/aatxe/markov"
readme = "README.md"

[dependencies]
rustc-serialize = "~0.2.9"
